{{- if .Values.main.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "n8n.fullname" . }}-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
data:
  {{- include "toEnvVars" (dict "values" .Values.main.config "prefix" "") | nindent 2 }}
{{- end }}
