{{- if .Values.webhook.enabled }}
{{- /* Validate Valkey/Redis configuration */}}
{{- include "n8n.validateValkey" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    {{- if .Values.webhook.deploymentLabels }}
    {{- toYaml .Values.webhook.deploymentLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.webhook.deploymentAnnotations }}
  annotations:
    {{- toYaml .Values.webhook.deploymentAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.webhook.autoscaling.enabled }}
  replicas: {{ .Values.webhook.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.webhook.deploymentStrategy.type }}
    {{- if eq .Values.webhook.deploymentStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ default "25%" .Values.webhook.deploymentStrategy.maxSurge  }}
      maxUnavailable: {{ default "25%" .Values.webhook.deploymentStrategy.maxUnavailable }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/type: webhook
  template:
    metadata:
      annotations:
        checksum/config: {{ print .Values.webhook .Values.main | sha256sum }}
        {{- with .Values.webhook.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "n8n.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/type: webhook
        {{- if .Values.webhook.podLabels }}
          {{ toYaml .Values.webhook.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "n8n.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webhook.podSecurityContext | nindent 8 }}
      {{- if .Values.webhook.initContainers }}
      initContainers:
      {{ tpl (toYaml .Values.webhook.initContainers) . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-webhook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.webhook.command }}
          command:
            {{- toYaml .Values.webhook.command | nindent 12 }}
          {{- else }}
          command: ["n8n"]
          {{- end }}
          {{- if .Values.webhook.commandArgs }}
          args:
            {{- toYaml .Values.webhook.commandArgs | nindent 12 }}
          {{- else }}
          args:
            - "webhook"
          {{- end }}
          ports:
            - name: http
              containerPort: {{ get (default (dict) .Values.webhook.config.n8n) "port" | default 5678 }}
              protocol: TCP
          {{- with .Values.webhook.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.webhook.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            {{- if .Values.main.config }}
            - configMapRef:
                name: {{ include "n8n.fullname" . }}-app-config
            {{- end }}
           {{- if .Values.main.secret }}
            - secretRef:
                name: {{ include "n8n.fullname" . }}-app-secret
            {{- end }}
            {{- if .Values.webhook.config }}
            - configMapRef:
                name: {{ include "n8n.fullname" . }}-webhook-config
            {{- end }}
           {{- if .Values.webhook.secret }}
            - secretRef:
                name: {{ include "n8n.fullname" . }}-webhook-secret
            {{- end }}

          env: {{ not (empty .Values.webhook.extraEnv) | ternary nil "[]" }}
            {{- range $key, $value := .Values.webhook.extraEnv }}
            - name: {{ $key }}
              {{- toYaml $value | nindent 14 }}
            {{- end }}
          lifecycle:
            {{- toYaml .Values.webhook.lifecycle | nindent 12 }}
          securityContext:
            {{- toYaml .Values.webhook.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /home/node/.n8n
          {{- if .Values.webhook.extraVolumeMounts }}
            {{- toYaml .Values.webhook.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if hasKey .Values.webhook "terminationGracePeriodSeconds" }}
      terminationGracePeriodSeconds: {{ .Values.webhook.terminationGracePeriodSeconds }}
      {{- end }}
      volumes:
        - name: "data"
          {{ include "n8n.pvc" . }}
        {{- if .Values.webhook.extraVolumes }}
          {{- toYaml .Values.webhook.extraVolumes | nindent 8 }}
        {{- end }}
{{- end }}
