{{- if and .Values.main.persistence.enabled (not .Values.main.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "n8n.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.main.persistence.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.main.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.main.persistence.size }}
  {{- if .Values.main.persistence.storageClass }}
  {{- if eq "-" .Values.main.persistence.storageClass }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.main.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
