{{- if .Values.worker.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-worker-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "toEnvVars" (dict "values" .Values.worker.secret "prefix" "" "isSecret" true) | nindent 4 }}

{{- end }}
