{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with .Values.webhook.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhook.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.webhook.service.port | default 80  }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/type: webhook
{{- end }}
