apiVersion: v2
name: n8n
version: 1.0.14
appVersion: 1.109.1
type: application
description: "Helm Chart for deploying n8n on Kubernetes, a fair-code workflow automation platform with native AI capabilities for technical teams. Easily automate tasks across different services."
home: https://github.com/8gears/n8n-helm-chart
icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
keywords:
  - Workflow Automation
  - Workflow
  - iPaaS
  - integration-framework
  - low-code-plattform
  - low-code
sources:
  - https://github.com/n8n-io/n8n
  - https://n8n.io/
maintainers:
  - name: 8gears
    email: contact@8gears.com
    url: https://github.com/8gears
  - name: n8n
    email: _@8gears.com
    url: https://github.com/n8n-io

dependencies:
  - name: valkey
    version: 2.4.7
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled

annotations:
  artifacthub.io/prerelease: "false"
  # supported kinds are added, changed, deprecated, removed, fixed and security.
  artifacthub.io/changes: |
    - kind: changed
      description: "Update n8n app version to 1.109.1"
